# .travis.yml for R project build.
#
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

# Drop server authenticity check to avoid hanging build: https://github.com/travis-ci/travis-ci/issues/1588
before_script:
  - echo -e "\nHost github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure:
